### ISSUE TITLE
Optional width and capitalization

### ISSUE THREAD

**Issue by pb-cdunn** [thegenemyers/DEXTRACTOR#11]
I'd like to diff output from dexta against the input fasta, but undexta does not capitalize or allow me to set the column-width. Not urgent, but helpful. Then, I *might* be able to use this instead of gzip within PacBio, since the speed-up and extra compression are considerable.

**Comment by thegenemyers** [comment]
Chris,

    I added the -U and -w options to undexta, exactly as for DB2fasta so 
you can control the
output.  I also add -U to undexqv in symmetry with DB2quiva.  Just 
checked them in to
Github and updated the man pages on the blog.  The changes were so small 
that I did not
test assuming I got it right.  If there are any problems please let me know.

    -- Gene

**Comment by pb-cdunn** [comment]
Thank you!
