### ISSUE TITLE
hdf5.h: No such file or directory

### ISSUE THREAD

**Issue by mictadlo** [thegenemyers/DEXTRACTOR#12]
Hello,

I installed `apt-get install libhdf5-dev` on Ubuntu 16.04, but I got the following error:

    # make
    gcc -O3 -Wall -Wextra -Wno-unused-result -fno-strict-aliasing -I/usr/local/hdf5/include -L/usr/local/hdf5/lib -o dextract dextract.c DB.c QV.c -lhdf5
    dextract.c:23:18: fatal error: hdf5.h: No such file or directory
    compilation terminated.
    Makefile:13: recipe for target 'dextract' failed
    make: *** [dextract] Error 1

I was not able to solve the above problem in the following 2 ways:

    ln -s /usr/lib/x86_64-linux-gnu/hdf5/serial/hdf5_hl.so /usr/lib/x86_64-linux-gnu/hdf5_hl.so 
    ln -s /usr/lib/x86_64-linux-gnu/hdf5/serial/hdf5_hl.a  /usr/lib/x86_64-linux-gnu/hdf5_hl.a 
    ln -s /usr/lib/x86_64-linux-gnu/hdf5/serial/hdf5.so /usr/lib/x86_64-linux-gnu/hdf5.so
    ln -s /usr/lib/x86_64-linux-gnu/hdf5/serial/hdf5.a /usr/lib/x86_64-linux-gnu/hdf5.a

or 

    ln -s /usr/lib/x86_64-linux-gnu/libhdf5_serial.so.10.1.0 /usr/lib/x86_64-linux-gnu/libhdf5.so 
    ln -s /usr/lib/x86_64-linux-gnu/libhdf5_serial_hl.so /usr/lib/x86_64-linux-gnu/libhdf5_hl.so 

What did I miss?

Thank you in advance.

Best wishes,

Mic

**Comment by psteinb** [comment]
Hi Michal,

if libhdf5-dev did bring the headers:

1) first check that it did (use
```
$ find / -name "hdf5.h"
```
or
```
$ locate hdf5.h #assumes that locate is configured/setup on your machine
```

2) you should not be required to supply -I to gcc. If hdf5.h landed in 
the system directories, gcc will pick it up. from what you posted, I 
would however guess that hdf5.h were NOT installed correctly.

3) if hdf5.h is installed but in non-standard paths, simply find it and 
add the path it is located in to the makefile of DEXTRACTOR.

Best,
P

**Comment by mictadlo** [comment]
Hi Peter,
I found it in ` ls /usr/include/hdf5/serial/`

	H5ACpublic.h    H5DataSet.h     H5FDmpi.h       H5IdComponent.h  H5PTpublic.h     H5f90i_gen.h           h5f_provisional.mod    h5p_provisional.mod
	H5AbstractDs.h  H5DataSpace.h   H5FDmpio.h      H5Include.h      H5PacketTable.h  H5overflow.h           h5fortran_types.mod    h5r.mod
	H5Apublic.h     H5DataType.h    H5FDmulti.h     H5IntType.h      H5Ppublic.h      H5pubconf.h            h5g.mod                h5r_provisional.mod
	H5ArrayType.h   H5DcreatProp.h  H5FDpublic.h    H5Ipublic.h      H5PredType.h     H5public.h             h5global.mod           h5s.mod
	H5AtomType.h    H5Dpublic.h     H5FDsec2.h      H5LTpublic.h     H5PropList.h     H5version.h            h5i.mod                h5t.mod
	H5Attribute.h   H5DxferProp.h   H5FDstdio.h     H5Library.h      H5Rpublic.h      h5_dble_interface.mod  h5im.mod               h5t_provisional.mod
	H5Classes.h     H5EnumType.h    H5FaccProp.h    H5Location.h     H5Spublic.h      h5a.mod                h5l.mod                h5tb.mod
	H5CommonFG.h    H5Epubgen.h     H5FcreatProp.h  H5Lpublic.h      H5StrType.h      h5a_provisional.mod    h5l_provisional.mod    h5test_kind_storage_size_mod.mod
	H5CompType.h    H5Epublic.h     H5File.h        H5MMpublic.h     H5TBpublic.h     h5d.mod                h5lib.mod              h5z.mod
	H5Cpp.h         H5Exception.h   H5FloatType.h   H5Object.h       H5Tpublic.h      h5d_provisional.mod    h5lib_provisional.mod  hdf5.h
	H5CppDoc.h      H5FDcore.h      H5Fpublic.h     H5OcreatProp.h   H5VarLenType.h   h5ds.mod               h5lt.mod               hdf5.mod
	H5Cpublic.h     H5FDdirect.h    H5Gpublic.h     H5Opublic.h      H5Zpublic.h      h5e.mod                h5o.mod                hdf5_hl.h
	H5DOpublic.h    H5FDfamily.h    H5Group.h       H5PLextern.h     H5api_adpt.h     h5e_provisional.mod    h5o_provisional.mod
	H5DSpublic.h    H5FDlog.h       H5IMpublic.h    H5PLpublic.h     H5f90i.h         h5f.mod                h5p.mod

How should I modify the Makefile?

**Comment by psteinb** [comment]
To be honest, the makefile is not really equipped to adapt to your environment. I'll send a PR with some suggestions. In any case, go to line 13:
`gcc $(CFLAGS) -I$(PATH_HDF5)/include -L$(PATH_HDF5)/lib -o dextract dextract.c DB.c QV.c -lhdf5`

convert it to:
`gcc $(CFLAGS) -I/usr/include/hdf5/serial/ -L/usr/lib/x86_64-linux-gnu/ -o dextract dextract.c DB.c QV.c -lhdf5`
that should do it

**Comment by ishfaq333** [comment]
> Thank for your fix. I needed as well
> 
> ```
> ln -s /usr/lib/x86_64-linux-gnu/libhdf5_serial.so.10.1.0 /usr/lib/x86_64-linux-gnu/libhdf5.so
> ln -s /usr/lib/x86_64-linux-gnu/libhdf5_serial_hl.so /usr/lib/x86_64-linux-gnu/libhdf5_hl.so
> ```

please help me with the same error I am getting in ubuntu 18
hdf5.h no such file or directory
