### ISSUE TITLE
compile error with zlib>=v1.2.5.2+

### ISSUE THREAD

**Issue by svm-zhang** [thegenemyers/DEXTRACTOR#15]
Hello Dr.Gene,

I was trying to compile DEXTRACTOR in docker with ubuntu:latest as base image. I used zlib-1.2.8 to compile DEXTRACTOR and got the following error (attached file):

[compile.err.txt](https://github.com/thegenemyers/DEXTRACTOR/files/671144/compile.err.txt)

Then I tried some older versions of zlib, and found out that this error did not show up with version <=v1.2.5.1. I thought this might be useful for other users and therefore I am posting it here.

If you could confirm this, could you please let other users know in the doc possibly?

Thanks,
Simo

**Comment by ebioman** [comment]
Hi
I run into a similar error today, trying to update DEXTRACTOR from an older version.
Where did you find actually such an old version, on github it start with v1.2.5.3 ?
Cheers

**Comment by svm-zhang** [comment]
Hello @ebioman, I found it on the zlib github repo and under releases tab:

[https://github.com/madler/zlib/releases](url)

Hope this helps.

cheers,
Simo

**Comment by ebioman** [comment]
Sorry, my bad I did not see the "Next" button on the page of versions...

Unfortunately I wont be able to install an older version of zlib on our cluster as it would break a lot of dependencies. Hoping for a fix.
Cheers

**Comment by svm-zhang** [comment]
Hello @ebioman, no worries at all, happens to me as well :) Glad to help!

cheers

**Comment by nathanhaigh** [comment]
I don't know C, but I managed to get rid of the error by applying this patch.

```diff
diff --git a/sam.c b/sam.c
index 830331f..9f6b0f3 100755
--- a/sam.c
+++ b/sam.c
@@ -168,15 +168,15 @@ error:
 int sam_eof(samFile *sf)
 { int c;

-  c = gzgetc(sf->ptr);
-  gzungetc(c,sf->ptr);
+  c = gzgetc((gzFile)sf->ptr);
+  gzungetc(c,(gzFile)sf->ptr);
   return (c < 0);
 }

 int sam_close(samFile *sf)
 { int ret;

-  ret = gzclose(sf->ptr);
+  ret = gzclose((gzFile)sf->ptr);
   free(sf->name);
   free(sf);
   return (ret != Z_OK);
@@ -284,7 +284,7 @@ static int sam_header_read(samFile *sf)

   dlen = 0;
   while (1)
-    { c = gzgetc(sf->ptr);
+    { c = gzgetc((gzFile)sf->ptr);
       if (c == EOF)
         break;
       gzungetc(c,sf->ptr);
```

**Comment by ebioman** [comment]
@nathanhaigh thanks a lot! Your patch seems to work, at least the error is gone.
Lets cross fingers that there will be no off-target effects ;)
Cheers

**Comment by svm-zhang** [comment]
@nathanhaigh it works for me as well. Thanks very much!

**Comment by DDDolle** [comment]
@nathanhaigh same here. Dextractor now compiles and runs. Thanks a lot!

Btw. has anyone else problems with the -o option?

I specified an output file with "-o[FASTA_FOLDER]/XZY.fasta" but instead of creating it there like the old 'dextract' did it just replaced the ".3.bax.h5" from the end of the h5 file with ".fasta" and dumped it in the working directory. Command was as follows:

"dextract -f -ofasta/m160720_184649_00127_c101011742550000001823222710211653_s1_p0.3.fasta m160720_184649_00127_c101011742550000001823222710211653_s1_p0.3.bax.h5"

**Comment by thegenemyers** [comment]
Dear all,

   Sorry for the problem with gzFile.  While @nathanhaigh's patch works, I've pushed a new version that fixes the problem properly.  Basically, gzFile is already a pointer, so I was mistakenly working with a pointer to a pointer, which works as long as you get past the compiler (mine didn't complain).

  @svm-zhang: could you pull the update and verify it compiles and works?  Also does it still work for older versions of z-lib?  Thank you.  Gene

**Comment by thegenemyers** [comment]
@DDDolle 

I fixed the -o option so that it should now perform as you expect it to.  Thanks for catching the mistake.  -- Gene

**Comment by DDDolle** [comment]
@thegenemyers Thanks a lot for the quick response!

Dirk

**Comment by svm-zhang** [comment]
Hello Dr. Gene,

The patch works with both new and old versions of z-lib. Thanks very much for the help.

cheers,
Simo
