### ISSUE TITLE
dex2DB.c fails to compile

### ISSUE THREAD

**Issue by danielhuson** [thegenemyers/DEXTRACTOR#16]
while installing tour DEXTRACTOR tool I came across this bug:

dex2DB.c: In function ‘main’:
dex2DB.c:666:28: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘==’ token
             char      *hdr == NULL;
                            ^
dex2DB.c:666:28: error: expected expression before ‘==’ token
dex2DB.c:769:17: error: ‘hdr’ undeclared (first use in this function)
                 hdr = rec->header;

**Comment by thegenemyers** [comment]
Hmm, sorry, I checked in a version where it should now be fixed. The == 
on line 666 should
have been an =.
   -- Gene

**Comment by danielhuson** [comment]
Thanks, that is what I assumed. See you in Leiden.
