### ISSUE TITLE
Error while loading shared libraries: libhdf5.so.10

### ISSUE THREAD

**Issue by leosegovia** [thegenemyers/DEXTRACTOR#17]
I get the following error when running dextract
`./dextract: error while loading shared libraries: libhdf5.so.10: cannot open shared object file: No such file or directory`

I know that is incorrect usage but shouldn't I get past library errors?

Any help would be appreciated

_PS: My HDF5 lib is under `/usr/local/hdf5`_

**Comment by psteinb** [comment]
Could be many things:

- did you upgrade your library but didn't relink dextractor?
-> for this, please run `ldd dextract` and post the results here!

- is the path of libhdf5.so.10 in your LD_LIBRARY_PATH?
-> please check by calling `echo $LD_LIBRARY_PATH` and compare the 
folders listed there with the path where libhdf5.so.10 is located.

- possibly relink dextract
-> before doing so, check that this line
https://github.com/thegenemyers/DEXTRACTOR/blob/master/Makefile#L2
points to the location of your `libhdf5.so`

**Comment by leosegovia** [comment]
I didn't relink dextractor DEXTRACTOR. When running `ldd extract` I get:
```
~/bin# ldd dextract                                                   
        linux-vdso.so.1 (0x00007ffc5d7da000)                                         
        libhdf5.so.10 => not found                                                   
        libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f1159f8f000)            
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f1159bf0000)            
        /lib64/ld-linux-x86-64.so.2 (0x0000560a27be0000)
```
Path for `libhdf5.so.10` is in my `LD_LIBRARY_PATH` just as specified in the Makefile.
```
~/bin# find /usr/local/hdf5/ -name libhdf5.so.10
/usr/local/hdf5/lib/libhdf5.so.10
```

When I installed hdf5, I ran `./configure --prefix=/usr/local/hdf5` to put all files under `/usr/local/hdf5` and then I `make && make install`. No errors returned.

**Comment by psteinb** [comment]
Can you please post your `LD_LIBRARY_PATH` in that session?

**Comment by leosegovia** [comment]
Sorry I'm not understanding your question. 
Do you want me to create the variable `LD_LIBRARY_PATH` in the **Makefile** and point it to my `libhdf5.so.10`?

Something like this: `LD_LIBRARY_PATH = /usr/local/hdf5/lib/libhdf5.so.10` 
What do I need to do this if I already have `PATH_HDF5 = /usr/local/hdf5` in the **Makefile**?

**Comment by leosegovia** [comment]
Nevermind, I finally understood what you meant. My `LD_LIBRARY_PATH` was not defined. 
I was able to define it by running:
`export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/hdf5/lib`

after that `ldd dextract` returned:
```
linux-vdso.so.1 =>  (0x00007ffc710c7000)
        libhdf5.so.10 => /usr/local/hdf5/lib/libhdf5.so.10 (0x00007f15269d9000)
        libz.so.1 => /lib64/libz.so.1 (0x00007f15267ba000)
        libc.so.6 => /lib64/libc.so.6 (0x00007f15263f9000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00007f15261f5000)
        libm.so.6 => /lib64/libm.so.6 (0x00007f1525ef2000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f1526ebe000)
```

Thanks for the help!

**Comment by dileepkunjaai** [comment]
> Can you please post your `LD_LIBRARY_PATH` in that session?
I also have same kind of issue with **---enable-shared** option . My LD_LIBRARY_PATH is here..


echo $LD_LIBRARY_PATH


/opt/intel/composerxe-2011.5.220/compiler/lib/intel64:/opt/intel/composerxe-2011.5.220/ipp/../compiler/lib/intel64:/opt/intel/composerxe-2011.5.220/ipp/lib/intel64:/opt/intel/composerxe-2011.5.220/compiler/lib/intel64:/opt/intel/composerxe-2011.5.220/mkl/lib/intel64:/opt/intel/composerxe-2011.5.220/tbb/lib/intel64//cc4.1.0_libc2.4_kernel2.6.16.21:/opt/mvapich2-1.8-r5423/intel/lib:/opt/intel/composerxe-2011.5.220/compiler/lib/intel64:/opt/intel/composerxe-2011.5.220/ipp/../compiler/lib/intel64:/opt/intel/composerxe-2011.5.220/ipp/lib/intel64:/opt/intel/composerxe-2011.5.220/compiler/lib/intel64:/opt/intel/composerxe-2011.5.220/mkl/lib/intel64:/opt/intel/composerxe-2011.5.220/tbb/lib/intel64//cc4.1.0_libc2.4_kernel2.6.16.21:/opt/intel/composerxe-2011.5.220/compiler/lib/intel64:/opt/intel/composerxe-2011.5.220/ipp/../compiler/lib/intel64:/opt/intel/composerxe-2011.5.220/ipp/lib/intel64:/opt/intel/composerxe-2011.5.220/compiler/lib/intel64:/opt/intel/composerxe-2011.5.220/mkl/lib/intel64:/opt/intel/composerxe-2011.5.220/tbb/lib/intel64//cc4.1.0_libc2.4_kernel2.6.16.21:/opt/intel/composerxe-2011.5.220/mpirt/lib/intel64:/opt/intel/composerxe-2011.5.220/mpirt/lib/intel64:/opt/intel/composerxe-2011.5.220/mpirt/lib/intel64

**Comment by thegenemyers** [comment]
The Makefile has two possible paths  for the HDF5 library in the 
variable PATH_HDF5 at the very top.
However, the path to the HDF5 is not consistently installed so you will 
have to ask your sysadmin where
it is and set the variable in the Makefile.  Sorry, I worked hard to 
remove all library dependencies from
the Daligner code base, but this dependence was unavoidable because 
PacBio used it for its older
file types.
    -- Gene

**Comment by Debabrataadak** [comment]
Hi,

I am getting the error message: 

"error while loading shared libraries: libhdf5_fortran.so.102: cannot open shared object file: No such file or directory"

Although I have installed the code with same hdf5 file without any error/werning message.  Library path of the hdf5 is added in  LD_LIBRARY_PATH.

My LD_LIBRARY_PATH is here:

/home/cdebabrata/software/libsharp/auto/lib:home/tghosh/softwares/cfitsio/lib:/home/tghosh/softwares/fftw-3.3.8/lib/:/home/tghosh/softwares/cfitsio/lib/:/home/tghosh/softwares/Healpix_3.40/lib/:/home/tghosh/softwares/libsharp/auto/lib/:/home/tghosh/softwares/NaMaster_new/lib:/home/tghosh/softwares/Healpix_3.40/src/C/subs:/home/tghosh/softwares/nag/cll6a23dhl/lib/:/home/cdebabrata/softwares/hdf5/lib:/opt/intel/parallel_studio_xe_2018.1.038/compilers_and_libraries_2018/linux/compiler/lib/intel64:/opt/intel/parallel_studio_xe_2018.1.038/compilers_and_libraries_2018/linux/mkl/lib/intel64:/opt/intel/parallel_studio_xe_2018.1.038/compilers_and_libraries_2018/linux/mpi/intel64/lib:/opt/libsharp-master/auto/lib:/opt/gsl-2.5/lib:/opt/cfitsio/lib:/opt/Healpix_3.40-source/lib:://home/tghosh/softwares/nag/cll6a23dhl/lib/
