### ISSUE TITLE
Removing SMRTbell and contaminations

### ISSUE THREAD

**Issue by mictadlo** [thegenemyers/DEXTRACTOR#18]
Hi,
After I convert h5 to fasta with `dextract -o SMRT1/Analysis_Results/*.bax.h5` can I use the following commands to remove SMRTbell and other contaminations in the following way or do you know a better way?

```
$ removesmartbell.sh in=$i out=${output}-rmsmrtbell.fasta split=t adapter=ATCTCTCTCTTTTCCTCCTCCTCCGTTGTTGTTGTTGAGAGAGAT

$ rename.sh in=$i out=${output}-rmsmrtbell-unique.fasta prefix=SMRT1

# Reference file contains all contaminations and I grab the unmapped reads which should be contamination free
$ bwa mem -t 4 -x pacbio $ref $i | samtools view -bS - | samtools sort - -o bwa/${output}.sorted.bam
$ samtools index bwa/${output}.sorted.bam
$ samtools view -b -f 4 bwa/${output}.sorted.bam  > bwa/unmapped_${output}.sorted.bam
$ bedtools bamtofastq -i bwa/unmapped_${output}.sorted.bam -fq bwa/unmapped_${output}.fastq

# Fastq to Fasta
$ bioawk -c fastx '{print ">"$name; print $seq}' bwa/unmapped_${output}.fastq > bwa/unmapped_${output}.fasta

# Keeping reads bigger than 1000 bp
$ bioawk -c fastx '{ if(length($seq) > 10000) { print ">"$name; print $seq }}' bwa/unmapped_${output}.fasta > bwa/unmapped_${output}-gt-10000 .fasta

$ fasta2DB DB bwa/unmapped_${output}-gt-10000 .fasta
```

Thank you in advance.

Michal

**Comment by svm-zhang** [comment]
Hello @mictadlo, I think with the new Sequel system, you can use `bax2bam` to convert your *.bax.h5. bax2bam should get you two bams: i) `X.subreads.bam`; ii) `X.scraps.bam`. As far as I know, the second BAM contains all contaminated reads (there is a tag labelled). 

You can then simply run `dextract` with filtration on the `X.subreads.bam` and get sequences (`X.subreads.fasta`) and quiver(`X.subreads.quiver`)/arrow(`X.subreads.arrow`) info.

I have compared the fasta file with the one obtained from `p_filter` module built in SMRTAnalysis 2.3.0, and they were highly consistent.

I hope this helps a bit.
