### ISSUE TITLE
dex2DB -e illegal option

### ISSUE THREAD

**Issue by svm-zhang** [thegenemyers/DEXTRACTOR#21]
Hello @thegenemyers,

I did not see -e option (EXPR=parse_filter() function) from the dex2DB.c. Does this support with dex2DB? Thanks.

Simo

**Comment by thegenemyers** [comment]
Yes, you are right, I forgot to add this option to dex2DB.  I'll take 
care of it in the
next few days.  Apologies.  -- Gene

**Comment by svm-zhang** [comment]
Thanks Dr. Gene!

**Comment by thegenemyers** [comment]
I just checked in a new version of the module where dex2DB now has the -e option.
I did not thoroughly test the code as the changes were quite straightforward.  If there
are any problems let me know right away and I'll fix them.  -- Gene

**Comment by svm-zhang** [comment]
Forgot to report back... it works. Thanks!
