### ISSUE TITLE
Arrow files for RS II files

### ISSUE THREAD

**Issue by mictadlo** [thegenemyers/DEXTRACTOR#22]
Hi,
I converted all my RS II files to Sequels BAM format with help of bax2bam tool.  Furthermore, I have also few Sequel files. 

Can I use the -a option in order to create for RS II BAM files and Sequel BAM files Arrow output files? 

Thank you in advance.

Michal

**Comment by thegenemyers** [comment]
Yes, that should work.  -- Gene
