### ISSUE TITLE
Erro when install & run "dextract" in ubuntu-i386

### ISSUE THREAD

**Issue by xingjianfeng100** [thegenemyers/DEXTRACTOR#23]
Hello，Sorry to disturb, but I met some mistakes when I installed  dextract , it said 
“expr.c: In function ‘terminal’:expr.c:138:27: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]       return (node(OP_INT,(Node *) x,NULL));
                           ^
expr.c: In function ‘eval_S’:expr.c:320:21: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]       return ((int) (int64) (v->lft));
                     ^
expr.c: In function ‘eval_X’:expr.c:370:21: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]       return ((int) (int64) (v->lft));
                     ^
QV.c: In function ‘Build_Table’:QV.c:127:23: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]     { uint64 symbol = (uint64) (node->lft);
                       ^
QV.c: In function ‘Huffman’:QV.c:174:33: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]             node[value].lft   = (HTree *) (uint64) i;
”
and when I run "dextract" for transfereing H5 file to FASTA ， it said “dextract: Cannot find *** with a Pacbio extension”, but the “*bax.h5” file is just in right place.
Could u give me some advice to solve it?  note: my operating system is ubuntu-16.04.3-desktop-i386
thank you so much!
I beg your pardon for my poor English.

**Comment by thegenemyers** [comment]
The compiler warnings shouldn't make any difference.  Apparently your 
machine
uses pointers that are not 8 bytes in size (which seems very strange).

What is the exact name of the file you give to dextract?  I'm assuming 
the * in
"*bax.h5 is a wild card.  The file is expected to have a name like 
foo.bax.h5 where
both dots (.) are important.  Please advise.

    -- Gene

**Comment by xingjianfeng100** [comment]
Thanks for your attention. but I'm sorry that it's the question of  my expression since I wanted to make it  more concise  originally. Apparently, the file name is correct for running "dextract".   The file name is "m161107_185146_00127_s1_p0.1.bax.h5" something like that.

**Comment by thegenemyers** [comment]
I took a look at the code in dextract for opening a file and also tested it on some .bax.h5 files I
have around.  Everything was fine.

In the error message "detract: Cannot find *** with a Pacbio extension", please tell me what the
*** is.  It should be the path and core name of the file (without the .bax.h5) extension.  In other words please send me the exact name of the file as it is in your file system, as you typed it in at the command line, and the entirety of the error message.

Thanks, Gene
