### ISSUE TITLE
Quality scores order in the .quiva file

### ISSUE THREAD

**Issue by vladimirsouza** [thegenemyers/DEXTRACTOR#25]
In the documentation, it is stated:

"... followed by the 5 quality value streams used by Quiver, one per line, where the order of the streams is: deletion QVs, deletion Tags, insertion QVs, substitution QVs, and last merge QVs."

But substitutionQVs and mergeQVs positions are swapped.
Cheers.

**Comment by thegenemyers** [comment]
Thanks and apologies, I'll change the doumentation.  -- Gene
