### ISSUE TITLE
Fails to build from source on some architectures (Debian Med)

### ISSUE THREAD

**Issue by shayandoust** [thegenemyers/DEXTRACTOR#27]
Hello,

I've been packaging DEXTRACTOR[1] in the Debian Med packaging team[2]. DEXTRACTOR is currently available in unstable and has now migrated into testing. There's just a question I have regarding building on some architectures. It builds on amd64 and a few other architectures but not on some other ones. An autobuild log can be found here[3]. The full log, for instance, of armel is here[4].

Any reason as to why this can happen? Is DEXTRACTOR not supported for some archs?

Kind regards,
Shayan Doust

[1]: https://salsa.debian.org/med-team/dextractor
[2]: https://wiki.debian.org/DebianMed
[3]: https://buildd.debian.org/status/package.php?p=dextractor
[4]: https://buildd.debian.org/status/fetch.php?pkg=dextractor&arch=armel&ver=1.0-2&stamp=1594818021&raw=0

**Comment by thegenemyers** [comment]
Forgive me, but I did not test Dextractor for all architectures, but 
only the ones
I have locally available.

All the problem builds seem to have to do with not being able to find 
the HDF5 library
on which Dextractor depends.  Unfortunately, this library does not occur 
in the same
place in all UNIX systems, and I did not write a make script that would 
find it on all
architectures.

   -- Gene

**Comment by shayandoust** [comment]
Many thanks for your prompt reply!

No worries! Thanks for the clarification. I wasn't aware that hdf5 installation locations differed compared to what was compiled. 

This commit[1] fixes this issue, and now the build report is as [this].

[1]: https://salsa.debian.org/med-team/dextractor/-/compare/6e256cdddb82baa573b4f02e969cb24a346f62a9...40ee9149529d498c26916bb54f8d004587b596a4
[this]: https://buildd.debian.org/status/package.php?p=dextractor
