### ISSUE TITLE
Not finding the hdf5.h file

### ISSUE THREAD

**Issue by HussainAther** [thegenemyers/DEXTRACTOR#5]
I have installed the dependency (hdf5: https://www.hdfgroup.org/HDF5/release/obtainsrc.html). However, when I run "make" on dextract, I get this error message:

ather@igsbimg:~/DEXTRACTOR-master$ make
gcc -O3 -Wall -Wextra -fno-strict-aliasing -I/usr/local/hdf5/include -L/usr/local/hdf5/lib -o dextract dextract.c DB.c QV.c -lhdf5
dextract.c:60:18: fatal error: hdf5.h: No such file or directory
 #include <hdf5.h>
                  ^
compilation terminated.
DB.c: In function ‘Load_QVs’:
DB.c:808:15: warning: ignoring return value of ‘fscanf’, declared with attribute warn_unused_result [-Wunused-result]
         fscanf(istub,DB_NFILE,&nfiles);
               ^
DB.c:812:19: warning: ignoring return value of ‘fscanf’, declared with attribute warn_unused_result [-Wunused-result]
           { fscanf(istub,DB_FDATA,&last,fname,prolog);
                   ^
DB.c:817:19: warning: ignoring return value of ‘fscanf’, declared with attribute warn_unused_result [-Wunused-result]
           { fscanf(istub,DB_FDATA,&last,fname,prolog);
                   ^
make: *** [dextract] Error 1

Do you know what could be causing this? Do I need to set some sort of environment variable to the location of hdf5.h file?

**Comment by psteinb** [comment]
Hi,

could you please check if /usr/local/hdf5/include/hdf5.h does exist? If 
not, please adapt /usr/local/hdf5/include/ to the path containing hdf5.h.

Best,
P

**Comment by HussainAther** [comment]
Mr. Steinbach,

There is no hdf5 folder in /usr/local/ at all.

What do you mean by adapting it to the path containing hdf5.h? Should I add "/usr/local/hdf5/include" to a certain variable?

I apologize for the inconvenience as I am a beginner at these issues.

Best,
Hussain

**Comment by HussainAther** [comment]
Never mind. I found the PATH in the Makefile and changed it so that it leads to the actual location of the library.

Thanks so much for your help.

Best,
Hussain

**Comment by HussainAther** [comment]
I successfully ran "make" (with some unused function errors)

However, when I try to run dextract, I get this error:

./dextract: error while loading shared libraries: libhdf5.so.10: cannot open shared object file: No such file or directory

**Comment by HussainAther** [comment]
Here is the output when I ran "make":

ather@igsbimg:~/DEXTRACTOR-master$ make
gcc -O3 -Wall -Wextra -fno-strict-aliasing -I/data/users/ather/hdf5-1.8.15-patch1/hdf5/include -L/data/users/ather/hdf5-1.8.15-patch1/hdf5/lib -o dextract dextract.c DB.c QV.c -lhdf5
dextract.c: In function ‘main’:
dextract.c:399:30: warning: ‘b.delLimit’ may be used uninitialized in this function [-Wmaybe-uninitialized]
                         { if (delQV[a] == d)
                              ^
dextract.c:488:11: note: ‘b.delLimit’ was declared here
   BaxData b;
           ^
DB.c: In function ‘Load_QVs’:
DB.c:808:15: warning: ignoring return value of ‘fscanf’, declared with attribute warn_unused_result [-Wunused-result]
         fscanf(istub,DB_NFILE,&nfiles);
               ^
DB.c:812:19: warning: ignoring return value of ‘fscanf’, declared with attribute warn_unused_result [-Wunused-result]
           { fscanf(istub,DB_FDATA,&last,fname,prolog);
                   ^
DB.c:817:19: warning: ignoring return value of ‘fscanf’, declared with attribute warn_unused_result [-Wunused-result]
           { fscanf(istub,DB_FDATA,&last,fname,prolog);
                   ^
gcc -O3 -Wall -Wextra -fno-strict-aliasing -o dexta dexta.c DB.c QV.c
DB.c: In function ‘Load_QVs’:
DB.c:808:15: warning: ignoring return value of ‘fscanf’, declared with attribute warn_unused_result [-Wunused-result]
         fscanf(istub,DB_NFILE,&nfiles);
               ^
DB.c:812:19: warning: ignoring return value of ‘fscanf’, declared with attribute warn_unused_result [-Wunused-result]
           { fscanf(istub,DB_FDATA,&last,fname,prolog);
                   ^
DB.c:817:19: warning: ignoring return value of ‘fscanf’, declared with attribute warn_unused_result [-Wunused-result]
           { fscanf(istub,DB_FDATA,&last,fname,prolog);
                   ^
gcc -O3 -Wall -Wextra -fno-strict-aliasing -o undexta undexta.c DB.c QV.c
DB.c: In function ‘Load_QVs’:
DB.c:808:15: warning: ignoring return value of ‘fscanf’, declared with attribute warn_unused_result [-Wunused-result]
         fscanf(istub,DB_NFILE,&nfiles);
               ^
DB.c:812:19: warning: ignoring return value of ‘fscanf’, declared with attribute warn_unused_result [-Wunused-result]
           { fscanf(istub,DB_FDATA,&last,fname,prolog);
                   ^
DB.c:817:19: warning: ignoring return value of ‘fscanf’, declared with attribute warn_unused_result [-Wunused-result]
           { fscanf(istub,DB_FDATA,&last,fname,prolog);
                   ^
gcc -O3 -Wall -Wextra -fno-strict-aliasing -o dexqv dexqv.c DB.c QV.c
DB.c: In function ‘Load_QVs’:
DB.c:808:15: warning: ignoring return value of ‘fscanf’, declared with attribute warn_unused_result [-Wunused-result]
         fscanf(istub,DB_NFILE,&nfiles);
               ^
DB.c:812:19: warning: ignoring return value of ‘fscanf’, declared with attribute warn_unused_result [-Wunused-result]
           { fscanf(istub,DB_FDATA,&last,fname,prolog);
                   ^
DB.c:817:19: warning: ignoring return value of ‘fscanf’, declared with attribute warn_unused_result [-Wunused-result]
           { fscanf(istub,DB_FDATA,&last,fname,prolog);
                   ^
gcc -O3 -Wall -Wextra -fno-strict-aliasing -o undexqv undexqv.c DB.c QV.c
DB.c: In function ‘Load_QVs’:
DB.c:808:15: warning: ignoring return value of ‘fscanf’, declared with attribute warn_unused_result [-Wunused-result]
         fscanf(istub,DB_NFILE,&nfiles);
               ^
DB.c:812:19: warning: ignoring return value of ‘fscanf’, declared with attribute warn_unused_result [-Wunused-result]
           { fscanf(istub,DB_FDATA,&last,fname,prolog);
                   ^
DB.c:817:19: warning: ignoring return value of ‘fscanf’, declared with attribute warn_unused_result [-Wunused-result]
           { fscanf(istub,DB_FDATA,&last,fname,prolog);
                   ^

**Comment by HussainAther** [comment]
It's working now. I had to set the LD_LIBRARY_PATH variable.
