### ISSUE TITLE
Streaming and pre-processing

### ISSUE THREAD

**Issue by pb-cdunn** [thegenemyers/DEXTRACTOR#7]
Ideas which could help us:
- [ ] Re-order reads so that SMRT cells are consecutive. (See thegenemyers/DAZZ_DB#21 and PacificBiosciences/FALCON#383 ) Choose one of these:
  1. Re-order in **dexta**, or
  1. Re-order in **undexta**, or
  1. Provide a new tool to re-order a `.dexta` file in-place.
- [ ] Allow **(un)dexta** to operate on fasta streams.
  - The compressed versions can be directly on-disk, if that helps you.
  - Ultimately, we might integrate **DEXTRACTOR** source-code into our **BAM2FASTA** writer.

**Comment by pb-cdunn** [comment]
We've found the cause of the re-ordering of the reads. Should be solvable in-house. Closing this feature-request.

**Comment by thegenemyers** [comment]
Chris,
    Curious as to how/why it was happening?  Was there a "good" reason
for the scramble?
    -- Gene
