### ISSUE TITLE
RQ required in header?

### ISSUE THREAD

**Issue by pb-cdunn** [thegenemyers/DEXTRACTOR#9]
```
$ dexta -vk foo.fasta
Processing 'foo' ...
dexta: Header line incorrectly formatted ?
```
I found that came from here:

    134               if (sscanf(slash+1,"%d/%d_%d RQ=0.%d\n",&well,&beg,&end,&qv) != 4)

    $ head foo.fasta
    >m151129_221014_sherri_c100947162550000001823216206251657_s1_p0/6/0_12833
    .... 

I don't think `RQ` should be required. Maybe store `0` by default, or ignore RQ if a default is supplied as a flag?

(I'm [investigating](PacificBiosciences/FALCON#383) whether we can use this instead of **gzip**. So far, it appears to be 4x faster with `4x` versus `2.9x` compression, a significant improvement.)

**Comment by thegenemyers** [comment]
Yes, overly restrictive.  The RQ will be optional in the next update.
    -- Gene

**Comment by thegenemyers** [comment]
FYI, I've pushed all the things that I said would be in the next update to
Github just a minute ago.  The only things unresolved now are the bug
in dexta/undexta on which I am waiting to hear back from you.
    -- Gene

**Comment by pb-cdunn** [comment]
Thanks. I'll merge your RQ change soon. (I'm traveling to Menlo Park now.)

Btw, 4x was an under-estimate. Here are timings for compressing a 14GB fasta from and to our *lustre* network filesystem:
```
$ time dexta -vk foo.fasta
Processing 'foo' ...
Done

real    0m52.560s
user    0m33.727s
sys     0m18.747s

$ time gzip -k --fast foo.fasta

real    7m30.484s
user    5m32.635s
sys     1m57.427s
```
That makes gzip look rather silly.
